name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make directory for build
      run: |
       mkdir build
       cd build
      
    - name: build
      run: cmake --build . %CMAKE_BUILD_FLAGS%
