name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies on ubuntu
      run: |
       sudo apt-get update
       sudo apt-get install ninja-build cmake
       ninja --version
       cmake --version
       gcc --version
          
    - name: make directory for build
      run: |
       mkdir build
       cd build
      
    - name: build
      run: cmake --build
